#!/usr/bin/env bash
# load balancer config

apt-get -y install update
apt-get -y install --no-install-recommends software-properties-common

add-apt-repository -y ppa:vbernat/haproxy-2.8

apt-get -y install haproxy=2.8.\*

rm /etc/haproxy/haproxy.cfg
cp /etc/haproxy/haproxy.cfg_backup /etc/haproxy/haproxy.cfg
# backup the config file
backup_file="/etc/haproxy/haproxy.cfg_backup"
if [ ! -f "$backup_file" ]; then
    cp /etc/haproxy/haproxy.cfg "$backup_file"
    echo "Backup created"
else
    echo "Backup file exist"
fi

frontend="frontend myfrontend \n\tbind *:80\n\tmode http\n\tdefault_backend  mybackend"
sed -i "/$frontend/d"   /etc/haproxy/haproxy.cfg
echo -e "$frontend" >>  /etc/haproxy/haproxy.cfg

mybackend="backend mybackend \n\tbalance roundrobin \n\tmode http\n\tserver server1 54.146.76.231:80 check \n\tserver server2 54.90.29.10:80 check"
sed -i "/$mybackend/d"   /etc/haproxy/haproxy.cfg
echo -e "$mybackend" >>  /etc/haproxy/haproxy.cfg

systemctl enable haproxy
service haproxy restart