#!/usr/bin/env bash
# Fixes server bug

apk update
apk add nginx

sed -i 's/^user .*/user nginx;/g' /etc/nginx/nginx.conf

sed -i 's/^.*listen .*/    listen 8080;/g' /etc/nginx/conf.d/default.conf

# change file ownership to nginx
chown -R nginx:nginx /var/lib/nginx /var/log/nginx /var/run/nginx

nginx -s reload

echo "Nginx is now running as nginx user, listening on all active IPs on port 8080."
