#!/usr/bin/env bash
# Fixes server bug
chmod 644 /etc/nginx/nginx.conf
sed -Ei 's/\s*#?\s*user .*/user nginx;/' /etc/nginx/nginx.conf
sed -Ei 's/(listen (\[::\]:)?80) /listen 8080 /' /etc/nginx/sites-enabled/default
# restart
su nginx -s /bin/bash -c 'service nginx restart'